package gui_elementos.feature.view;

import gui_elementos.feature.control.FeatureControl;
import javax.swing.JFrame;
import gui_elementos.feature.utils.FileControl;
import gui_elementos.feature.utils.HelperTable;
import gui_elementos.feature.vo.Gherkin;

/**
 *
 * @author mtptulamac007
 */
public class View extends JFrame {

    private final FileControl fileControl;
    private FeatureControl featureControl;
    private HelperTable helperTB;
    private String featureText;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        setLocationRelativeTo(null);
        fileControl = new FileControl();
        helperTB = new HelperTable(tbGherkin);
        featureText = "";
        txtScreen.setEditable(false);
        btnAnalizar.setEnabled(checkEdit.isSelected());
    }

    private void infoAnalisis(String txtInfoFeature) {
        txtScreen.setText(txtInfoFeature);
        listView.setSelectedItem("Select");
        helperTB.clearTable();
        featureControl = new FeatureControl(txtInfoFeature);
        if (!txtInfoFeature.isEmpty()) {
            listView.setSelectedItem("All");
            nameFeature.setText(featureControl.getNameFeature());

        }
    }

    private void setDataFeature(String fac, FeatureControl _featureControl) {
        txtTotalGherkis.setText(fac);
        txtManual.setText(_featureControl.gherkinsManuales() + "");
        txtFactibleManual.setText(_featureControl.gherkinsOutline() + "");
        txtBackSmoke.setText("" + helperTB.getFactibles());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        listView = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnArchivo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGherkin = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtScreen = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        checkEdit = new javax.swing.JCheckBox();
        btnAnalizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalGherkis = new javax.swing.JTextField();
        txtBackSmoke = new javax.swing.JTextField();
        txtFactibleManual = new javax.swing.JTextField();
        txtManual = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        nameFeature = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Menu")));

        listView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "All", "Outlines", "Manual", "@baken-smoke", "Manual-Factible" }));
        listView.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listViewItemStateChanged(evt);
            }
        });
        listView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listViewActionPerformed(evt);
            }
        });

        jLabel1.setText("Ver:");

        btnArchivo.setText("Archivo");
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(listView, 0, 134, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), null));

        tbGherkin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGherkin.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tbGherkin);

        txtScreen.setColumns(20);
        txtScreen.setRows(5);
        jScrollPane3.setViewportView(txtScreen);

        checkEdit.setText("Editar contenido");
        checkEdit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkEditStateChanged(evt);
            }
        });

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkEdit)
                .addGap(28, 28, 28)
                .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEdit)
                    .addComponent(btnAnalizar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Información")));
        jPanel4.setToolTipText("");
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("# Gherkin Totales");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 25, -1, -1));

        jLabel3.setText("# Gherkis Manual");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setText("# Gherkis Fact - Manual");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel5.setText("# @baken-smoke");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtTotalGherkis.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtTotalGherkis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtTotalGherkis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 50));

        txtBackSmoke.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtBackSmoke.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtBackSmoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 90, 50));

        txtFactibleManual.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtFactibleManual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtFactibleManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, 50));

        txtManual.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        txtManual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 50));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 133, 10));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 133, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 131, 11));

        nameFeature.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        nameFeature.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(nameFeature))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameFeature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo que se ejecuta al cambiar el valor seleccionado de la lista
     */
    private void listViewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listViewItemStateChanged
        // TODO add your handling code here:
        int total = 0;
        int fac = 0;
        int contador = 0;
        switch (listView.getSelectedItem().toString()) {
            case "All" -> {
                helperTB.clearTable();
                helperTB.setHeader("Tag,Name,Factible,Jira,Outline");
                contador = 0;
                int ma = 0;
                int facManu = 0;
                for (Gherkin item : featureControl.listGherkin()) {
                    if (item.isIsOutline()) {
                        total += featureControl.expandScenarioOutlines(item.getBlok()).size();
                        for (String i : featureControl.expandScenarioOutlines(item.getBlok())) {
                            contador++;
                            if (item.isIsFactible()) {
                                fac++;
                                if (item.isIsManual()) {
                                    facManu++;
                                }
                            } else if (item.isIsManual()) {
                                ma++;
                            }
                            helperTB.addItemOutline(item, i, contador);

                        }
                    } else {
                        if (item.isIsFactible()) {
                            fac++;
                            if (item.isIsManual()) {
                                facManu++;
                            }
                        } else if (item.isIsManual()) {
                            ma++;
                        }
                        contador++;
                        helperTB.addItem(item, contador);
                    }

                }
                txtBackSmoke.setText(fac + "");
                txtFactibleManual.setText(facManu+"");
                txtTotalGherkis.setText("" + contador);
                txtManual.setText(""+ma);
            }
            case "Outlines" -> {
                helperTB.clearTable();
                helperTB.setHeader("Tag,Name,Factible,Jira,Outline");
                contador = 0;
                for (Gherkin item : featureControl.listGherkin()) {

                    if (item.isIsOutline()) {
                        txtFactibleManual.setText(featureControl.expandScenarioOutlines(item.getBlok()).size() + "");

                        for (String i : featureControl.expandScenarioOutlines(item.getBlok())) {
                            contador++;
                            helperTB.addItemOutline(item, i, contador);
                        }
                    }
                }
            }
            case "Manual" -> {
                helperTB.clearTable();
                helperTB.setHeader("Tag,Name,Factible,Jira,Outline");
                contador = 0;
                int manual = 0;
                for (Gherkin item : featureControl.listGherkin()) {
                    if (item.isIsManual()) {
                        manual++;
                        txtFactibleManual.setText(featureControl.expandScenarioOutlines(item.getBlok()).size() + "");
                        if (item.isIsOutline()) {
                            for (String i : featureControl.expandScenarioOutlines(item.getBlok())) {

                                contador++;
                                helperTB.addItemOutline(item, i, contador);
                            }
                        } else {
                            total += 1;
                            contador++;
                            helperTB.addItem(item, contador);
                        }
                    }
                }
                txtManual.setText(manual + "");
            }
            case "@baken-smoke" -> {
                helperTB.clearTable();
                helperTB.setHeader("Tag,Name,Factible,Jira,Outline");
                int f = 0;
                contador = 0;
                for (Gherkin item : featureControl.listGherkin()) {
                    if (item.isIsFactible()) {

                        txtFactibleManual.setText(featureControl.expandScenarioOutlines(item.getBlok()).size() + "");
                        if (item.isIsOutline()) {
                            for (String i : featureControl.expandScenarioOutlines(item.getBlok())) {
                                f++;
                                contador++;
                                helperTB.addItemOutline(item, i, contador);
                            }
                        } else {
                            f++;
                            contador++;
                            helperTB.addItem(item, contador);
                        }
                    }
                }
                txtManual.setText(f + "");
            }
            case "Manual-Factible" -> {
                helperTB.clearTable();
                helperTB.setHeader("Tag,Name,Factible,Jira,Outline");
                int f = 0;
                contador = 0;
                for (Gherkin item : featureControl.listGherkin()) {
                    if (item.isIsFactible() && item.isIsManual()) {

                        txtFactibleManual.setText(featureControl.expandScenarioOutlines(item.getBlok()).size() + "");
                        if (item.isIsOutline()) {
                            for (String i : featureControl.expandScenarioOutlines(item.getBlok())) {
                                f++;
                                contador++;
                                helperTB.addItemOutline(item, i, contador);
                            }
                        } else {
                            f++;
                            contador++;
                            helperTB.addItem(item, contador);
                        }
                    }
                }
                txtManual.setText(f + "");
            }

        }
        setDataFeature(total + "", featureControl);
    }//GEN-LAST:event_listViewItemStateChanged

//GEN-FIRST:event_btnArchActionPerformed
 
//GEN-LAST:event_btnArchActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        featureText = fileControl.mostrarContenido();
        infoAnalisis(featureText);

    }//GEN-LAST:event_btnArchivoActionPerformed

    private void listViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listViewActionPerformed
    private void statusElemnetCheck(boolean flag) {
        btnArchivo.setEnabled(flag);
        checkEdit.setSelected(flag);
        txtScreen.setEditable(flag);
    }
    private void checkEditStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkEditStateChanged
        btnAnalizar.setEnabled(checkEdit.isSelected());
        txtScreen.setEditable(true);

    }//GEN-LAST:event_checkEditStateChanged

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:
        statusElemnetCheck(false);
        btnAnalizar.setEnabled(false);
        checkEdit.setSelected(false);

        infoAnalisis(txtScreen.getText());
    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JCheckBox checkEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> listView;
    private javax.swing.JLabel nameFeature;
    private javax.swing.JTable tbGherkin;
    private javax.swing.JTextField txtBackSmoke;
    private javax.swing.JTextField txtFactibleManual;
    private javax.swing.JTextField txtManual;
    private javax.swing.JTextArea txtScreen;
    private javax.swing.JTextField txtTotalGherkis;
    // End of variables declaration//GEN-END:variables
}
